# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mappilogue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NMapsMap'

  # Pods for Mappilogue

  target 'MappilogueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MappilogueUITests' do
    # Pods for testing
  end

end
